
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: reactive-fundamentals
  data:
    mongodb:
      database: demo
      host: localhost
      port: 27017
